version: '2.1'
services:
  mongo:
    image: mongo:6
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: short_url
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: short_urls
  redis:
    image: redis:7.0.11
    ports:
      - 6379:6379
  app:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - redis
      - mongo
    environment:
      MONGODB_URI: mongodb://short_url:password@mongo:27017
      REDIS_HOST: redis:6379
      GIN_MODE: release
